### ISSUE TITLE
Not sure about this additional power

### ISSUE THREAD

**Issue by irajivagrawal** [adityadatar8/9040-STEAMPunks-Alpha#1]
https://github.com/adityadatar8/9040-STEAMPunks-Alpha/blob/29ca12b2845fbf1d1744c7b3bed7221f44a0d287/Autonomous/LightWork.java#L58

Is there some issue with the backwheel motor?  Maybe we should create a constant that can be tweaked from top of the code similar to other constants.

**Comment by adityadatar8** [comment]
Yes we put that constant in after testing out the code because we noticed that as the robot was strafing, it was also turning because of the backright motor having less torque. The addition of this constant would allow the vertical components to cancel out and eliminate turning during strafing. We definitely can make a constant variable for this at the top.

**Comment by adityadatar8** [comment]
Update: LightWork was the code from quite a while earlier, and at that time the backright motor was having issues. Later on, I'm not sure what exactly changed physically with the robot but the backright motor no longer had issues with torque, so that's why the more recent Autonomous programs like Lexus and Roadster don't have the offset.
